# Generated by Django 4.1.5 on 2023-01-28 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ghgh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tentg', models.CharField(max_length=800)),
                ('theloai', models.CharField(max_length=1200)),
                ('chucnang', models.CharField(max_length=1500)),
            ],
        ),
    ]
